import type { Metadata } from "next";
import ServiceWorkerRegister from "../components/ServiceWorkerRegister";
import "../styles/globals.css";
import LayoutQueryProvider from "@/components/layout/provider";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "MEYDI SHOP",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ServiceWorkerRegister />
        <LayoutQueryProvider>
          <Toaster
            toastOptions={{
              className: "",
              duration: 5000,
              removeDelay: 1000,
              style: {
                background: "#000",
                color: "#fff",
              },
              success: {
                style: {
                  background: "#161f1c",
                  color: "#45c273",
                },
                duration: 3000,
                iconTheme: {
                  primary: "#1d332c",
                  secondary: "#45c273",
                },
              },
              error: {
                style: {
                  background: "#100708",
                  color: "#de4f4f",
                },
                duration: 3000,
                iconTheme: {
                  primary: "#39191c",
                  secondary: "#de4f4f",
                },
              },
            }}
            position="bottom-right"
          />
          {children}
        </LayoutQueryProvider>
      </body>
    </html>
  );
}
